name = "bitprophet-ingestor"
main = "index.js"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

# The `observability` object becomes a table in TOML
[observability]
enabled = true

[placement]
mode = "smart"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "7c9455e046a646188ec8e6450256d932"

[triggers]
# The cron syntax is standard. This runs at the start of every minute.
crons = ["* * * * *"]
